### ISSUE TITLE
CBC feedback

### ISSUE THREAD

**Issue by erikng** [erikng/Agile-Brewing-Issues#13]
- ~~I tried adding a bean with a roast date May 19th and didn't work. No error msg or crash, the bean profile was just no showing up. Changing the roast date to something more recent worked.~~ new UI in v37
- ~~I would add a field in the bean profile for the processing method.~~ coming in v37
- Grind size: the current scale is not useful for my current grinders. The Mythos scale is 0 to 9 with subdivisions of 0.2, e.g., 7.2 or 8.4. The Kinu uses 3 numbers for grind size like 1:3:2. So you see the current scale is not applicable and I would suggest something more universal. Perhaps you could just allow the decimal from the current scale to be finer in steps of 0.1 instead of 0.5. 
- I would also have an option to set the grind size as burr gap in microns, e.g., 120  μm, with an extra binary field specifying if the burr gap is from lock or from chirp. 
- Add an extra field to specify the grinder and the burrs, useful for people with multiple grinders and burrs
- ~~Allow the brew temp to go lower than 87 C. I don't personally use lower temps, but know people who go as low as 80 C.~~ coming in v37
- ~~Allow for higher ratios than 1:30. Filter2.0 or allonges can go to even up to 1:15.~~ coming in v37
- ~~Allow for longer shot times than 60 s.  Some do shots up to 250 s!~~ coming in v37
- Preinfusion: I would like to have more options. I exclusively do dynamic blooms, where preinfusion time is not considered a variable. Instead, I would like to specify the water fill rate in ml/s during preinfusion,  peak pressure, exit pressure, water  rate in ml/s during the shot. 
- ~~Add an extra field that automatically calculates the extraction yield % (EY) from the TDS and brew ratio.~~ This already exists, but only appears when you set TDS.
- add a section for used water specifying the GH and KH values and what was used to get there, like epsom salt, sodium bicarbonate, etc.

**Comment by erikng** [comment]
~~For the first issue, there should be a warning in the bean view that it will not show up unless you increase the "bean roast age limit" in the settings tab.~~

**Comment by erikng** [comment]
- ~~I noticed something else, actual yield is limited to 48. I would increase its limit, or even making limitless. It appears to be limited to 3x dosage weight.~~

**Comment by czegledi** [comment]
- ~~Drink template bug: I can't set the brew temp when using Celsius.~~ 
- ~~Bean processing methods should be: natural, washed, honey, wet hulled, anaerobic, carbonic maceration.~~ 
- ~~Default dosage could be something more common, e.g., in the 16-18 g range.~~ 
- Allow for "tamp weight" to be hidden from the UI
- Allow for "group head pre-heated" to be hidden from the UI
- Allow for "portafilter pre-heated" to be hidden from the UI
- Allow for "pre-infususion time" to be hidden from the UI
- Allow for "drink time" to be hidden from the UI
- Allow for "channeling" to be hidden from the UI
- Allow for "puck consistency" to be hidden from the UI

**Comment by erikng** [comment]
> Drink template bug: I can't set the brew temp when using Celsius.

This will be fixed in the next release

> Default dosage could be something more common, e.g., in the 16-18 g range.

This will be 16g in the next release

> Bean processing methods should be: natural, washed, honey, wet hulled, anaerobic, carbonic maceration

I am going to add wet hulled, anaerobic and carbonic maceration to the list but keep the others for now

This will be in the next release

I will address those hidden UI elements in a following release

**Comment by erikng** [comment]
@czegledi I'm going to close this issue as I've taken these bits of feedback and put them into their own issues to track separately.

**Comment by czegledi** [comment]
Some more suggestions:
-it would be nice to see the temperature and the additional comments in the shot history. Also the GH/KH of the used water if/when this will be implemented.
- I am getting some errors for the displayed yield extraction in the shot history. It shows a certain value when editing the drink, but then a different value is shown in the shot history. 
- It would be nice to be able to attach photos to the beans avatar. For instance I would take a picture of the bag. 
- The possibility of inputing the brix measurement instead of TDS and calculating the TDS and Extraction Yield from that. The formula is TDS = 0.85*Brix. 
- I actually quite liked the previous icons that were less colorful, more inline with iOS settings menu, etc. I would be nice to be able to select themes for the app. (I realize that this may be far fetched, but I am being nit-picking here :)
- Selection sliders/menus: there are different types of selecting different numbers: gring size is one, dosage is another type,  temperature is a slider. Is there a reason for this diversity? Personally, I don't quirw like the grind selection, dosage, preinfusion, extraction time, and I would rather have them the same style as dosage. 
- Not sure what is the intent with the extraction procentage. It's not a standard metric and it took me a while to get what it actually is, but I don't find that it brings too much info.

**Comment by erikng** [comment]
> I am getting some errors for the displayed yield extraction in the shot history. It shows a certain value when editing the drink, but then a different value is shown in the shot history.

I can't recreate this.

> Selection sliders/menus: there are different types of selecting different numbers: gring size is one, dosage is another type, temperature is a slider. Is there a reason for this diversity? Personally, I don't quirw like the grind selection, dosage, preinfusion, extraction time, and I would rather have them the same style as dosage.

As I told you on Discord, this will look a lot better on iOS 16. I agree that on iOS 15.5 they don't look good, but these exact picker styles look pretty awesome on iOS 16 and for these particular selectors, I think they are faster than the dosage one. Sent you a video

> Not sure what is the intent with the extraction procentage. It's not a standard metric and it took me a while to get what it actually is, but I don't find that it brings too much info.

The intent here is to show you how close you got to the ratio you wanted. For example when I stopped brewing my shot, I get anywhere from 1-4 grams of additional espresso. This is a good indicator to me when I look at the previous day(s) shot how much finer of a grind size I should attempt to use.

I'm going to close this again and take the other comments into tickets to track them.
